title: Sky Cloud Backup
author: Involts
name: Involts
description: A Minecraft Backup that supports both Bedrock and Java.
google_analytics: true
show_descriptions: true # set to true to show descriptions
baseurl: /Sky-Cloud-Backup
# Before publishing the site to github-pages, replace the varable of baseur
# if you have brought a doman remove the varable above 
# Links in Header
theme: jekyll-theme-fica
header:
  header_name_1: Download
  header_link_1: https://github.com/Involts/Sky-Cloud-Backup/releases/download/Alpha_0.3/Sky.Cloud.Backup.Alpha.0.3.zip
  header_name_2: Releases
  header_link_2: /Releases/
  header_name_3: About
  header_link_3: /About/
fica:
  date_format: "%b %-d, %Y"
      
plugins:
 - jekyll-feed
 - jekyll-seo-tag
exclude:
 - README.md
