title: Sky Cloud Backup
author: Involts
name: Involts
description: A Minecraft Backup that supports both Bedrock and Java.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: "Sky-Cloud-Backup"
minima:
  date_format: "%b %-d, %Y"
  social_links:
    github:  Involts
plugins:
 - jekyll-feed
 - jekyll-seo-tag
