title: Sky Cloud Backup
author: Involts
name: Involts
latest_download: "https://github.com/Involts/Sky-Cloud-Backup/releases/download/Alpha_0.3/Sky.Cloud.Backup.Alpha.0.3.zip"
description: A Minecraft Backup that supports both Bedrock and Java.
Latest_version: "https://github.com/Involts/Sky-Cloud-Backup/releases/download/Alpha_0.3/Sky.Cloud.Backup.Alpha.0.3.zip"
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: "/Sky-Cloud-Backup"
minima:
  date_format: "%b %-d, %Y"
  social_links:
    github:  Involts  
plugins:
 - jekyll-feed
 - jekyll-seo-tag
