#!/bin/sh

set -e

echo "Building the site....."
script/server

if test -e "./_site/index.html";then
  echo "the site is built!"
  rm -Rf _site
else
  echo "The site didn't build"
  exit 1
fi

gem build jekyll-theme-fica.gemspec
